version: "3.8"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data 
    ports:
      - "5434:5434"

  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    command: start --optimized
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      
      KC_IMPORT_REALM: /opt/keycloak/data/import/realm.json
    volumes:
      - keycloak_data:/opt/keycloak/data  
      - ./realm-export.json:/opt/keycloak/data/import/realm.json 
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data: 
  keycloak_data:  